### ISSUE TITLE
Jet problem generator: pressure is not written in VTK output file when -s option is on

### ISSUE THREAD

**Issue by omerbr** [PrincetonUniversity/athena-public-version#16]
When compiling with the following flags:
**python configure.py --prob=jet --flux=default --coord=cartesian -s -omp**
and then running with the regular athinput.jet file the pressure is not written properly into the output file:
for example opening the first output file in python, the pressure should be 0.006:
**In [118]: A=vtk('jet.block0.out2.00000.vtk')
In [119]: A[3]['press'][0,125,:10]
Out[119]: 
array([3.46944695e-18, 3.46944695e-18, 3.46944695e-18, 3.46944695e-18,
       3.46944695e-18, 3.46944695e-18, 3.46944695e-18, 3.46944695e-18,
       3.46944695e-18, 3.46944695e-18])**

When compiling without the -s flag the pressure is written fine:
**python configure.py --prob=jet --flux=default --coord=cartesian -omp**
Then opening in python:
**In [120]: A=vtk('jet.block0.out2.00000.vtk')
In [121]: A[3]['press'][0,125,:10]
Out[121]: 
array([0.006, 0.006, 0.006, 0.006, 0.006, 0.006, 0.006, 0.006, 0.006,
       0.006])**

**Comment by tomidakn** [comment]
The input file provided for the jet problem is not designed for special relativity. It uses non relativistic formulae for calculating the total energy and other conservative variables, so it does not return the expected pressure when converted back to primitives. Also, because the speed of light in the code unit is 1 and this problem generator sets the jet velocity to 1, the gamma factor diverges there.  

@c-white, can you confirm? I'm afraid I am not the best person to answer this question.

**Comment by c-white** [comment]
Everything above is correct. To make a relativistic jet, one should make a new problem generator based on `jet.cpp` with the formulas in the "initialize conserved variables" section and the `phydro->u(IEN,k,j,i) += ...` formula in the "initialize interface B" section are modified. They should match what is done in `PrimitiveToConserved()` in `eos/adiabatic_mhd_sr.cpp`. In fact, one can set the primitives `phydro->w(...)` in the problem generator, along with the magnetic fields, and then call `PrimitiveToConserved()` to set the conserved values automatically (it is the conserved values only that the code cares about in this stage).

Additionally, the input file should be modified to not have the jet moving at the speed of light.

I'll also add that are floors that can and usually should be specified in the input file, under the `<hydro>` section, but apparently are not present in `athinput.jet`. In any configuration, Athena will impose hard limits on density and pressure via `dfloor` and `pfloor`, defaulting to something around 1e-35 if not specified. In SR, one has the extra option of `gamma_max`, defaulting to 1000, which limits the velocity of the fluid. In SR MHD, there are also `sigma_max` and `beta_min`, which default to infinity and zero if not specified. If set to other values, they will increase the density and/or pressure where the magnetic field becomes very strong (never altering the field). All of these might help with robustness in certain situations.

I don't know that this is explicitly spelled out anywhere, but a design decision of the code was to not clutter Newtonian problem generators with relativistic physics, especially since some of the problem generators are quite long and complicated, and making them work in relativity too (if that even makes sense) would essentially double their size and be filled with `if (RELATIVISTIC_DYNAMICS)` and `if (GENERAL_RELATIVITY)` statements. As a result, the problem generators that are included with the code are all Newtonian unless their name is prefixed with `gr_`. All of these work in GR, the ones that don't involve black holes work in SR too, and none of them work with Newtonian physics. (We might add more traps to detect these incompatibilities at compile time.)

**Comment by omerbr** [comment]
Thanks Chris & Kengo
So basically you mean that in this setup of jet.cpp I cannot compile with
-s option, is that correct?
Is there any problem generator that sets up a problem for sr?
I see only gr pgens.

**Comment by c-white** [comment]
Yes, `gr_linear_wave.cpp` and `gr_shock_tube` work both in GR and SR, and they are designed to be run with the input files in `inputs/hydro_sr/` and `inputs/mhd_sr/`.

**Comment by omerbr** [comment]
thanks, I'll look there,
will let you know if it works!

**Comment by omerbr** [comment]
Hi Guys
Another question, hope its not a dumb one.
In the relativistic case I see that you define this 4-vector of the
magnetic field
(which is not really a magnetic field)  in the following way:

        Real bt = bbx*ux + bby*uy + bbz*uz;
        Real bx = (bbx + bt * ux) / ut;
        Real by = (bby + bt * uy) / ut;
        Real bz = (bbz + bt * uz) / ut;

Now my question is as follow:
The magnetic field is defined at face centers, while the 4-velocity is
defined at the cell center.
So isn't that a problem to write them both quantities in a single
expression without interpolation ?
Doesn't it make more sense to first interpolate the 4-velocity to the face
centers and then calculate bt,bx,by,bz?

**Comment by c-white** [comment]
Whenever b is calculated from B and velocity, everything will always be interpolated to the same place first. For example when calculating magnetic pressure in a cell, the function `CalculateCellCenteredField()` in `field/field.cpp` will be called to make a new array with cell-centered B given face-centered B. Actually in the above lines B and v are constant in space, so we don't have to worry about the staggered mesh. (Note the quantities we store are just B and v, not `(B)*(face area)` or `(v)*(cell volume)`.)

**Comment by omerbr** [comment]
got you, and thanks for the info on the grid interpolate function.
Just to make sure , the 4-vector b is defined at the face center right?

**Comment by c-white** [comment]
b is always a temporary derived quantity, and it will be defined in different places in different contexts. So inside the Riemann solver it will be on the faces, but in primitive->conserved calculations it will be at cell centers. b never persists beyond these limited scopes.

**Comment by omerbr** [comment]
Wait, in the jet.cpp file b field is provided as part of the conserved
quantities in  MeshBlock::ProblemGenerator(),
and as part of the primitive values in JetInnerX1().
Now in both cases there are loops that look like this for b_y :

    for (int k=ks; k<=ke; ++k) {

    for (int j=js; j<=je+1; ++j) {

#pragma simd

      for (int i=1; i<=(NGHOST); ++i) {

        Real rad = sqrt(SQR(pco->x2v(j)-x2_0) + SQR(pco->x3v(k)-x3_0));

        if(rad <= r_jet){

          b.x2f(k,j,is-i) = by_jet;

        } else{

          b.x2f(k,j,is-i) = b.x2f(k,j,is);

        }

      }


and like this for b_x:

    for (int k=ks; k<=ke+1; ++k) {

    for (int j=js; j<=je; ++j) {

#pragma simd

      for (int i=1; i<=(NGHOST); ++i) {

        Real rad = sqrt(SQR(pco->x2v(j)-x2_0) + SQR(pco->x3v(k)-x3_0));

        if(rad <= r_jet){

          b.x3f(k,j,is-i) = bz_jet;

        } else{

          b.x3f(k,j,is-i) = b.x3f(k,j,is);

        }

      }

    }}

So this tells me that b here is defined at *face center* not cell center.
So how does this fit what you just wrote?

**Comment by c-white** [comment]
In all relativistic contexts, I try to use `b` to mean the 4-vector b, and `bb` to mean the standard B field. However, any files that are not explicitly relativistic, like jet.cpp, will always use B and will call it `b`.

**Comment by omerbr** [comment]
Still confused about the location where b and bb are defined in SR and NR
cases.
Let me try to summarize how I understand what the input parameters should
be based on jet.cpp.
Please correct me where I'm wrong. I divide the cases to NR and SR:

1) in the NR case :
MeshBlock::ProblemGenerator(): sets the initial conditions in *lab frame
conserved variable.*
Hydrodynamic quantities: mass density, energy density, momentum (rho*v)
are *cell center*,
Magnetic fields *face center.*

JetInnerX1(): sets the boundary condition in *lab frame primitive variable.*
Hydrodynamic quantities: mass density, pressure, 3-velocity are *cell
center,*
Magnetic fields* face center*.
----------------------------------------------------------------------
2) in the SR case
MeshBlock::ProblemGenerator() sets the *rest frame conserved variables*:
Hydrodynamic quantities: mass density, energy density, momentum
(rho*u) are *cell
center, defined in rest frame*,
4-vector Magnetic fields  *face center, *where b in the expression for the
4-vector* is the lab frame b.*

JetInnerX1(): sets the boundary condition in *rest frame primitive
variable.*
Hydrodynamic quantities: mass density, pressure, 3-velocity are *cell
center, ** defined in rest frame. *
4-vector Magnetic fields* face center**, *where b in the expression for the
4-vector* is the lab frame b.*
----------------------------------------------------------------------
Is that a correct way to summarise the properties of the required
parameters?
Thanks a lot!!!!!
Omer

**Comment by c-white** [comment]
The NR case is correct.

For SR, all conserved variables are in the lab frame, as are the primitive velocities. The primitive variables are rho, pgas, v^i. The conserved variables are gamma*rho, gamma^2 * (rho + Gamma/(Gamma-1) * pgas + b^2) - b^t * b^t - (pgas + b^2/2), gamma^2 * (rho + Gamma/(Gamma-1) * pgas + b^2) * v^i - b^t * b^i, where b has to be calculated from B and v at the cell center. But b is just a temporary variable in these formulas.

Also for setting magnetic fields, you only ever need to worry about B at faces. Athena doesn't know about b at all, and there's no where to set it. (jet.cpp uses the variable name `b` for B.) So for initial conditions set B at every face touching an active cell. For the boundary condition set B at the faces in the ghost zone.

**Comment by omerbr** [comment]
On Tue, Dec 11, 2018 at 3:55 AM Chris White <notifications@github.com>
wrote:

> The NR case is correct.
>
> For SR, all conserved variables are in the lab frame, as are the primitive
> velocities. The primitive variables are rho, pgas, v^i. The conserved
> variables are gamma*rho, gamma^2 * (rho + Gamma/(Gamma-1) * pgas + b^2) -
> b^t * b^t - (pgas + b^2/2), gamma^2 * (rho + Gamma/(Gamma-1) * pgas + b^2)
> * v^i - b^t * b^i, where b has to be calculated from B and v at the cell
> center. But b is just a temporary variable in these formulas.
>
So these are the conserved variables equivalent to [rho, e , mv] , but what
about the magnetic field? I assume I need to provide also b^i, b^j, b^k?
Just to be clear, b = [b^t ,b^i , b^j, b^k] is the 4-vector ,  while b^2 =
b_i b^i right? abd B is the lab frame magnetic field?
also to calculate b you use B, is B the lab frame magnetic field?

> Also for setting magnetic fields, you only ever need to worry about B at
> faces. Athena doesn't know about b at all, and there's no where to set it.
> (jet.cpp uses the variable name b for B.) So for initial conditions set B
> at every face touching an active cell. For the boundary condition set B at
> the faces in the ghost zone.
>
Regarding the boundary condition I did not understand you point.
First, I need to provide the primitive variables here. Are these variables
calculated in the rest frame or in the lab frame?
Namely do I provide [rho, p and v] or [gamma*rho, gamma^2*p and v] ?
Second, what about the magnetic field in this case , do I provide lab frame
B or 4-vector b, and is that defined on the face center as well?

Sorry for all the questions
O.

**Comment by omerbr** [comment]
Ok I reread your answer an seems that I missed the primitives part.
"The primitive variables are rho, pgas, v^i"

However my question about the magnetic fields still stand.
1) What magnetic fields do I use for the conserved variables , is it the
4-vector b
2) is b^2 in the conserved variables expressions the square of the four
vector  (b^i b_i).
3) for the calculation of 4-vector b , do I use the lab frame B?
4) What magnetic field do I use for the primitive variables,

thanks again,
O.

**Comment by omerbr** [comment]
Ok reread things again :), I keep answering my own questions.
4-vector b is just for the conserved parameters enthalpy and momentum.
For the conserved variable,  B, you use bbx, bby , bbz, which is the lab(?)
frame B at face center right?
Primitive B I still don't know what to use, is it the same as conserved?
cheers
O.

**Comment by felker** [comment]
Hi @omerbr 👋 
Thanks for reporting the issue regarding the ambiguity of NR vs SR problem generators. Based on your feedback, we are going to add more compatibility checks in the next public release of the code.

@c-white has agreed to answer any more questions you may have over email, so I have locked this Issue for now.
