### ISSUE TITLE
Is MHD in spherical coordinates actually supported?

### ISSUE THREAD

**Issue by leftaroundabout** [PrincetonUniversity/athena-public-version#3]
Athena, as advertised, can run in spherical coordinates, even when the poles are included in the computation domain. Nice!

E.g. Sedov explosion (aka hydro blast):

![sedov-spherical-simple](https://cloud.githubusercontent.com/assets/1528675/24906477/2a542b1e-1eb8-11e7-85f9-786ab37a284a.gif)

https://github.com/leftaroundabout/athena-public-version/commit/656ed8ae65580de807448ce1ba5ae711c295a743#diff-996f90439ea6a4a98a169d70ffde9f4d

Maybe that's a bit of a trivial case because the isotropy means we don't actually have any vectors pointing in ϑ direction, which might explain why we don't see any problems at the pole (mind, other codes already have problems with this test!)

Making it an MHD blast, unfortunately, also leads to trouble in Athena:

![mhdblast-spherical-pole-singularity0000](https://cloud.githubusercontent.com/assets/1528675/24914701/47dfed40-1ed5-11e7-8dc1-babc602835dd.png)

All I've changed here (perhaps naïvely) was turning on the magnetic field.

https://github.com/leftaroundabout/athena-public-version/commit/4a0f1687e4a6edf67c75363fbe4825ae4e5988c1#diff-996f90439ea6a4a98a169d70ffde9f4d

This time, the singularity at the pole is impossible to miss. The code still runs ok for a while, until around _t_ = 2·10<sup>-2</sup> the CFL slows it down ever more, more or less converging to a complete standstill.

Have I merely missed some configuration option that would be necessary to get this working, or is there actually a fundamental problem for MHD at the poles? This would hardly be surprising – neither Flash or Pluto can actually do MHD in spherical coordinates, in fact I know no code that manages it without correction tricks (computation in two 90° rotated systems). But Athena seems to rather emphasize its coordinate-system flexibility, so it would be interesting to know whether it is actually up to the task.

**Comment by tomidakn** [comment]
Thank you for the report. Actually, the code itself supports MHD in spherical coordinates even with the poles, but that particular problem generator (blast wave) does NOT support magnetic fields in spherical coordinates. In order to run the MHD blast wave in spherical coordinates, you need to initialize the magnetic fields accordingly using the vector potential. I'm sorry it's a bit confusing. We should add a proper initial condition, or at least add a trap to warn the user.

Instead, to demonstrate the MHD in spherical coordinates including the poles, you can try the field_loop_pole test (please configure the code with `-b` and `--prob field_loop_pole`, and then run it with `inputs/mhd/athinput.field_loop_poles`). This is a standard B-field loop advection test, but the loop goes across the pole.

Also, please note that a singularity is a singularity anyway - here "support" means it does not crash or does not behave badly, but please do not expect it is very accurate around the poles. It may still cause numerical problems such as short timesteps.

**Comment by c-white** [comment]
The blast wave problem generator will better support MHD in curvilinear coordinates in future releases of the code.

For the present version, the code is assigning

<var>B</var><sup>1</sup> = <var>B</var><sub>0</sub> cos(<var>&psi;</var>)
<var>B</var><sup>2</sup> = <var>B</var><sub>0</sub> sin(<var>&psi;</var>)
<var>B</var><sup>3</sup> = 0

for some angle <var>&psi;</var>, typically 30 degrees. This was done whether the components were Cartesian, cylindrical, or spherical, and in spherical coordinates this field is poorly behaved near the pole (in fact it has a magnetic monopole density that diverges there). In order for the curvilinear fields to match the Cartesian field, the components should be changed to

<var>B</var><sup><var>r</var></sup> = <var>B</var><sub>0</sub> (cos(<var>&psi;</var>) cos(<var>&phi;</var>) - sin(<var>&psi;</var>) sin(<var>&phi;</var>))
<var>B</var><sup><var>&phi;</var></sup> = -<var>B</var><sub>0</sub> (sin(<var>&psi;</var>) cos(<var>&phi;</var>) + cos(<var>&psi;</var>) sin(<var>&phi;</var>))
<var>B</var><sup><var>z</var></sup> = 0

in cylindrical coordinates and

<var>B</var><sup><var>r</var></sup> = <var>B</var><sub>0</sub> |sin(<var>&theta;</var>)| (cos(<var>&psi;</var>) cos(<var>&phi;</var>) - sin(<var>&psi;</var>) sin(<var>&phi;</var>))
<var>B</var><sup><var>&theta;</var></sup> = <var>B</var><sub>0</sub> cos(<var>&theta;</var>) (cos(<var>&psi;</var>) cos(<var>&phi;</var>) - sin(<var>&psi;</var>) sin(<var>&phi;</var>))
<var>B</var><sup><var>&phi;</var></sup> = -<var>B</var><sub>0</sub> (sin(<var>&psi;</var>) cos(<var>&phi;</var>) + cos(<var>&psi;</var>) sin(<var>&phi;</var>))

in spherical coordinates.

With these changes, the code at least runs with a relatively constant timestep.

**Comment by leftaroundabout** [comment]
Thanks for the replies. I should have noticed that the initial magnetic field was not homogeneous.

By properly transforming the initial field (https://github.com/leftaroundabout/athena-public-version/commit/c6c1c9a330e3430a05a9abe20d35b8065ba1e2b8), I was indeed able to run the simulation with relatively constant time step.
https://github.com/leftaroundabout/athena-public-version/tree/fde7abef3a2e3327936b976a8eb44dbecaff3df3
Sure enough, there are notable artifacts at the poles

![blast-spherical-pole-singularity0000](https://cloud.githubusercontent.com/assets/1528675/25134091/f722720e-244e-11e7-99e4-6747b46adaa4.png)

but in the equatorial plane the result essentially corresponds to what the MHD blast also does in cartesian coordinates.

![mhdblast-cartesian png0001](https://cloud.githubusercontent.com/assets/1528675/25134153/212bc262-244f-11e7-9132-0f3790a47c91.png) ![mhdblast-spherical png0000](https://cloud.githubusercontent.com/assets/1528675/25134154/212d3016-244f-11e7-838e-41ced259d76d.png)

(I would attribute the discrepancy more to the omitted “planet interior” region in the middle, than to the pole issues. Of course it's not a conclusive test anyway, at such low resolution etc..)

@c-white I wonder, did you just use a different sign convention for orientation of the angle _ψ_ in the above equations, or is this something Athena-specific I should be aware of? When I transformed the original homogeneous **B**-field, I ended up with

_B_<sup>_r_</sup> = _B_<sub>0</sub> · |sin(_θ_)| · (cos(_ψ_) · cos(_φ_) + sin(_ψ_) · sin(_φ_))
_B_<sup>_θ_</sup> = _B_<sub>0</sub> · cos(_θ_) · (cos(_ψ_) · cos(_φ_) + sin(_ψ_) · sin(_φ_))
_B_<sup>_φ_</sup> = _B_<sub>0</sub> · (sin(_ψ_) · cos(_φ_) − cos(_ψ_) · sin(_φ_))

which corresponds to your equation with _ψ_ ↦ -_ψ_.

Also, what it the advantage to taking the absolute-value of sin(_θ_), which should in the domain be non-negative anyway?

Again, thank you!

**Comment by c-white** [comment]
Indeed the sign of <var>&psi;</var> should be flipped in what I wrote above.

As for the absolute value, you're right that changes nothing here. It's just a habit of mine from considering the volume element as <var>r</var><sup>2</sup> |sin(<var>&theta;</var>)| d<var>r</var> d<var>&theta;</var> d<var>&phi;</var>. This is important for dealing with the ghost zones across the pole, since they are in the sin(<var>&theta;</var>) < 0 part of the coordinate system but internally the code chooses the convention that volumes there are still positive.
