### ISSUE TITLE
Update Wiki and input file with `deref_count` -> `derefine_count`

### ISSUE THREAD

**Issue by jlippuner** [PrincetonUniversity/athena-public-version#31]
The `deref_count` parameter explained in the wiki (https://github.com/PrincetonUniversity/athena-public-version/wiki/Adaptive-Mesh-Refinement) seems to have been renamed to `derefine_count` (see line 37 of `mesh_refinement.cpp`). I have been getting unexpected results because I used `deref_count` in my input file and thought I'm setting that parameter. But that setting was quietly ignored and the default value of 10 was used instead. The wiki and `hydro/athinput.slotted_cylinder2d_refined` input file should be updated.

It might also be worth considering adding a functionality to warn the user if there are options in the input files that are not being used, instead of silently ignoring them. I realize that this might be non-trivial to implement.

**Comment by felker** [comment]
Thanks.

Actually, I believe it was *always* `derefine_count` (right @tomidakn? see https://github.com/PrincetonUniversity/athena/commit/24696cbcb84ac58420bd338b72b4d877d91d9cd8). The `deref_count` in the Wiki and that one input file is a typo. Fixed on the private repo. 

I don't think that we will add your suggested functionality, since several input files can be used for multiple types of simulations and will have ignored/unused parameters in some of those configurations.
