### ISSUE TITLE
Add DOI to version tags?

### ISSUE THREAD

**Issue by morganemacleod** [PrincetonUniversity/athena-public-version#40]
Hi folks,

As I understand it, tagging versions with a DOI is one of the best ways that we can add specificity to our software citations. 

One way to do this is with Zenodo. A link to the DOIs can then be placed into the readme for the code. Work using the software can then cite directly the specific version being used. This is becoming the requested practice for AAS journals. 

I was recently reading about this here: https://github.com/AASJournals/Tutorials/blob/master/Repositories/UsingRepositories.md

Thanks for considering -- this could be another good way for all of the people who have put effort into developing this fantastic resource to get credit as it is deserved! 

Morgan

**Comment by felker** [comment]
Thanks for the suggestion. I have added the Zenodo webhook, so the archival should be automatic for the next release. I would have to upload `.zip` of all the existing releases. 

There would have to be an internal discussion about whether or not to mint a DOI for Athena++, and if so, what authorship conventions to use. Maybe "The Athena++ team"? Seems like Enzo might have automatically pulled the authors directly from some ranking of the GitHub contributors, which would be even easier: https://zenodo.org/record/3469922

**Comment by felker** [comment]
Done; thanks for the suggestion. See https://zenodo.org/record/4455880 

10.5281/zenodo.4455879 is the Concept DOI, which erroneously resolves to the oldest release right now, but that might be fixed in the future in Zenodo. I have emailed them directly about it. Regardless, the next Athena++ release will automatically be added in Zenodo via the webhook integration, and that DOI will correctly redirect to the latest version at that point. 

10.5281/zenodo.4455880 is the v21.0 DOI, which should be cited for all works that used this latest version of Athena++ to produce the results.

**Comment by morganemacleod** [comment]
Awesome!! Thanks for taking the effort to do this. I hope it's a useful step for our publications in terms of being more precise w/versioning and reproducibility!
