### ISSUE TITLE
Optically-thin cooling

### ISSUE THREAD

**Issue by drbetelgeuse** [PrincetonUniversity/athena-public-version#43]
Hello,
I'm interested in optically-thin cooling feature as in base Athena code. Do you have plans to implement it in Athena++?

**Comment by c-white** [comment]
There will not be a general flag where you can turn on optically thin cooling, since the form of that cooling will vary greatly from problem to problem. However, optically thin cooling is simply a source term in the energy equation (and in momentum for relativity). The guide for writing your own source function is [on the wiki](https://github.com/PrincetonUniversity/athena-public-version/wiki/Problem-Generators#User-Defined-Physical-Source-Term), and it includes a simple example for a cooling function.

**Comment by drbetelgeuse** [comment]
Oh, I just missed it expecting to find it as an additional physics feature. Thank you for help, c-white.
