### ISSUE TITLE
Looking at adjacent meshblocks

### ISSUE THREAD

**Issue by rcdannen** [PrincetonUniversity/athena-public-version#56]
In my current project, I want to "look back" to what's stored in meshblocks containing points interior to the point I'm at (so all points between where I'm at in x1 and x1min) without altering them.  This is easy to do if everything is one meshblock, but I'm not the correct way to do if there are multiple meshblocks.

I've see points such as pmb->prev or pmb->next, so my intuition is to use those and just check where I'm at.  And this seems to terminate if I do something like:

```
while(this_pmb != NULL){
  // do stuff without changing the contents of the meshblock
  this_pmb = this_pmb->prev;
}
```

Is this the best way to go about this?  Are there any good examples of this in the provided pgens?

Thanks in advanced!

**Comment by felker** [comment]
Are you doing this only in the `ProblemGenerator`? What exactly do you mean by "check where I'm at"?

The MeshBlocks are stored in a doubly-linked list. There is no reliable guarantee on how they are ordered in this list with respect to physical location when mesh refinement is used (correct @tomidakn ?), so your approach would have to search every node in the linked list to exhaustively find the blocks that satisfy your criteria.

Even for a uniform mesh without refinement, the Z-ordering makes it impossible to just look back through the linked list to search lower `x1` blocks; see Figure 1 from the method paper.

**Comment by rcdannen** [comment]
Are you doing this only in the ProblemGenerator? 

I would be doing this either the work before, in, or after loops.

What exactly do you mean by "check where I'm at"?

I meant to start at the last x1 position of "this_pmb" and check to make sure it's interior to where I started.

If that's the case about there being no easy ordering, then I guess the only thing I could do is start at the end of the link list and navigate check meshblock, correct?

**Comment by felker** [comment]
> If that's the case about there being no easy ordering, then I guess the only thing I could do is start at the end of the link list and navigate check meshblock, correct?

That would certainly work, but there might be more efficient (and less general) ways of collecting your info depending on what it is.

**Comment by c-white** [comment]
Indeed, you would need to go through the entire list in both directions, and for each block check if it contains any cells you are looking for.

But even this will not work when using using MPI, since you won't have access to the blocks on other MPI ranks (aka Meshes). In the parallel case some additional MPI communication would need to be added.

The "best" way will depend on more details about what you are trying to get. (It sounds like this might be a central star illuminating a partially transparent medium?)

**Comment by rcdannen** [comment]
This is the case.  I'm trying to track optical depth between our location and the central source, and I need to know the state of the gas interior as well.

**Comment by c-white** [comment]
I have not done anything like this, though someone out there probably has. Here's my outline of what to do in the case of MPI:

The code structure looks something like

```
Mesh::InitUserMeshData()
for each MeshBlock in Mesh: MeshBlock::InitUserMeshBlockData()
for each MeshBlock in Mesh: MeshBlock::ProblemGenerator()
for each timestep:
  for each MeshBlock in Mesh: update conserved variables in first substep
  for each MeshBlock in Mesh: user source term
  for each MeshBlock in Mesh: find primitives
  for each MeshBlock in Mesh: update conserved variables in second substep
  for each MeshBlock in Mesh: user source term
  for each MeshBlock in Mesh: find primitives
  for each MeshBlock in Mesh: MeshBlock::UserWorkInLoop()
  Mesh::UserWorkInLoop()
Mesh::UserWorkAfterLoop()
```

The appropriate place for MPI calls is `Mesh::UserWorkInLoop()`, since it is called exactly once per step (using `MeshBlock::UserWorkInLoop()` could cause the code to hang). So `Mesh::UserWorkInLoop()` will need to gather all the data from any of the MeshBlocks it contains that needs to be passed around. The data will then need to be passed with MPI calls, either all-to-all or something more efficient but more complicated. `Mesh::UserWorkInLoop()` will do the communication, and `Mesh::InitUserMeshData()` will have to set up the recurring MPI calls.

Whenever you need to use the data (either in the user source term to modify things or in `MeshBlock::UserWorkInLoop()` for analysis), the MeshBlock can grab whatever is stored on its Mesh through the `pmy_mesh->ruser_mesh_data` pointers. Because of the code structure, this information might be considered one timestep out of date, but the only way around that is to add new Mesh functions and associated task list tasks in the right places in the loop.

What exactly is passed around depends on what you need and whether mesh refinement is present. It might be as simple as populating an array of size (num blocks in r) * (num global cells in theta) * (num global cells in phi) with attenuations up to each r-face of the MeshBlocks, and making sure every Mesh has a copy of this array.

**Comment by rcdannen** [comment]
Thank you for the detailed response.  I'll try to give this a try.  

To be more specific about what I'm trying to do, I'm want to use the data (density, pressure, and velocity) from other mesh blocks to update a user area that tracks optical depth.  Can I define a user array at the Mesh level?

**Comment by c-white** [comment]
Yes, user arrays can live on the Mesh. See https://github.com/PrincetonUniversity/athena-public-version/wiki/Problem-Generators#User-Defined-Data-Field
