### ISSUE TITLE
Unphysical values when simulating high Mach flows

### ISSUE THREAD

**Issue by Yotag** [PrincetonUniversity/athena-public-version#9]
Hello! its me again.
I am trying to run a simulation, and sometimes it break down to something obviously not physical.
I have alot of variables in my simulation so I managed to replicate this problem using the Blast code, basicly I just set some density ball in the origin and gave it velocity
os the grid is 128^3, using 64^3 meshblocks with 8 proccesors
 x?min=-10,x?max=10.
ambiant density is 1,ratio is 10
ambient pressure is 10, ratio is 1.
and I added 100 velocity in the x2 direction upon intializing.
after 0.01 time I get this:
![visit0000](https://user-images.githubusercontent.com/31243916/31672557-9419947a-b365-11e7-9712-15ec963ffc8d.png)

Which is exactly what I got on my own simulation.
What is this bug, and how can it be solved?
Thanks alot,
Yotam.

**Comment by tomidakn** [comment]
The sound speed in the cold region is about sqrt(1/10)~ 0.3, so your flow has Mach ~ 300. Unfortunately, this is an extremely severe situation for Eulerian hydrodynamics codes. So I do not think this is a bug but just a limitation of the code. Please try with lower speed, say, Mach ~ 20.

**Comment by Yotag** [comment]
this is at 17 mach 
![visit0001](https://user-images.githubusercontent.com/31243916/31675372-1c3a064e-b36d-11e7-99f7-4a49da8ba17f.png)
although abit late, the bug still occurs.
this is merely a reproduction of the bug I got on a diffrent simulation, in which the mach number was even lower.

**Comment by tomidakn** [comment]
Thanks for the update. Again, please understand this is still a very severe situation for Eulerian codes. 

Such a high Mach number flow produces strong rarefaction waves (and shocks), and the gas easily hits the default density/pressure floor (1.2e-35). The floor keeps the code running, but it cannot save the simulation in this case.

Possible solutions are:
1. Try a more robust Riemann solver: try HLLC if you are using Roe as Roe is very fragile in this situation, and if it does not work consider HLLE although it is very diffusive.
2. Raise the floors but not too high so that the floors do not affect the region if interest too much. You have to be careful because the floors can change the conclusion.
3. Modify the limiter to more robust one, such as minmod.

**Comment by beresnyak** [comment]
Flow away from the wall will produce vacuum at Mach =2/(gamma-1)
